---
title: "ToDo"
author: "Shannon Rush"
output: pdf_document
---

[X] Data Processing
[X] Create shiny view with check boxes for genres
[X] React to checkboxes
[X] check all
[X] uncheck all
[X] Change date range
    [X] add monthadded to Rdata
    [X] add date range selector to UI
    [X] if date range <= 1 year use dateadded instead of monthadded 
    [X] subset data on daterange (use dateadded)
[X] Add tabs
    [X] conditionally renderUI based on active tab
[X] By Gender
    [X] Genre switches to radio buttons
    [X] pretty up plot
[X] refactor out repeating code
[X] By Age Group
[] By location
    [X] geocode locations in dataset
    [X] display map with d3js
    [X] decide on map to use
    [X] sidebar: genre checkboxes and dates
        [X] refactor checkbox toggle buttons to get name from button for multiple checkbox sets
    [X] add a test data point 
    [X] render points from single genre
    [X] color points by genre
        [X] add color array to json mapped to genre
    [X] style map to better show colors
    [X] color checkbox labels in map.colors
    [] map actions that are less jarring
    [] BUG: when no genres selected adventure still loaded
    [] style map
    [] add d3 and topojson files to project instead of fetching
[] By location v2
    [X] display google map
    [X] can relative frequency be displayed with bubbles?
    [X] Add circle symbol marker to map for test
    [X] re-add color labels
    [X] build location data
    [X] remove markers
    [] scale markers
[] pull out unused js/css
[] add tests
[] add reactive values
[X] resolve includeCSS problem
    
[] Use map colors for all plots
[] Pretty up title and add explanatory text and links
[] Improve styling
